#!/bin/bash

# compile js
./pack
# gulp bump --patch

# build
cordova build ios --device --release

# pack
xcrun \
  -sdk iphoneos PackageApplication \
  -v "platforms/ios/build/device/农惠网.app" \
  -o "/Users/eteng/nhw360-enterprise-demo.ipa"

# sign & provision
sigh resign "/Users/eteng/nhw360-enterprise-demo.ipa" \
  -i "iPhone Distribution: Beijing Eteng Technology Co., Ltd" \
  -p "signatures/InHouse_com.eteng.nhw360edemo.mobileprovision"
