#!/bin/bash

# compile js
./pack
# gulp bump --patch

# build
cordova build ios --device --release

# pack
xcrun \
  -sdk iphoneos PackageApplication \
  -v "platforms/ios/build/device/农惠网.app" \
  -o "/Users/eteng/nhw360-enterprise.ipa"

# sign & provision
sigh resign "/Users/eteng/nhw360-enterprise.ipa" \
  -p "nhw360_distribution_appstore.mobileprovision"
