#!/bin/bash

OUTPUT_PATH="/Users/eteng/nhw360.ipa"

# compile js
./pack
# gulp bump --patch

# build
cordova build ios --device --release

# pack
xcrun \
  -sdk iphoneos PackageApplication \
  -v "platforms/ios/build/device/农惠网.app" \
  -o $OUTPUT_PATH

# sign & provision
sigh resign $OUTPUT_PATH \
  -p "signatures/nhw360_distribution_appstore.mobileprovision"
